INSERT INTO exercises(exercise,calories) VALUES ('Cycling, <10 mph, leisure bicycling',236);
INSERT INTO exercises(exercise,calories) VALUES ('Cycling, 16-19 mph, very fast, racing',708);
INSERT INTO exercises(exercise,calories) VALUES ('Unicycling',295);
INSERT INTO exercises(exercise,calories) VALUES ('Stationary cycling, moderate',413);
INSERT INTO exercises(exercise,calories) VALUES ('Stationary cycling, vigorous',620);
INSERT INTO exercises(exercise,calories) VALUES ('Calisthenics, vigorous, pushups, situps',472);
INSERT INTO exercises(exercise,calories) VALUES ('Calisthenics, light',207);
INSERT INTO exercises(exercise,calories) VALUES ('Circuit training, minimal rest',472);
INSERT INTO exercises(exercise,calories) VALUES ('Weight lifting, body building, vigorous',354);
INSERT INTO exercises(exercise,calories) VALUES ('Weight lifting, light workout',177);
INSERT INTO exercises(exercise,calories) VALUES ('Health club exercise',325);
INSERT INTO exercises(exercise,calories) VALUES ('Stair machine',531);
INSERT INTO exercises(exercise,calories) VALUES ('Rowing machine, light',207);
INSERT INTO exercises(exercise,calories) VALUES ('Rowing machine, moderate',413);
INSERT INTO exercises(exercise,calories) VALUES ('Ski machine',413);
INSERT INTO exercises(exercise,calories) VALUES ('Aerobics, low impact',295);
INSERT INTO exercises(exercise,calories) VALUES ('Aerobics, high impact',413);
INSERT INTO exercises(exercise,calories) VALUES ('Aerobics, general',318);
INSERT INTO exercises(exercise,calories) VALUES ('Jazzercise',354);
INSERT INTO exercises(exercise,calories) VALUES ('Stretching, hatha yoga',236);
INSERT INTO exercises(exercise,calories) VALUES ('Mild stretching',148);
INSERT INTO exercises(exercise,calories) VALUES ('Instructing aerobic class',354);
INSERT INTO exercises(exercise,calories) VALUES ('Running, 5 mph (12 minute mile)',472);
INSERT INTO exercises(exercise,calories) VALUES ('Running, cross country',531);
INSERT INTO exercises(exercise,calories) VALUES ('Track and field (high jump, pole vault)',354);
INSERT INTO exercises(exercise,calories) VALUES ('Badminton',266);
INSERT INTO exercises(exercise,calories) VALUES ('Basketball game, competitive',472);
INSERT INTO exercises(exercise,calories) VALUES ('Fencing',354);
INSERT INTO exercises(exercise,calories) VALUES ('Football, competitive',531);
INSERT INTO exercises(exercise,calories) VALUES ('Sailing, competition',295);
INSERT INTO exercises(exercise,calories) VALUES ('Ski mobiling',413);
INSERT INTO exercises(exercise,calories) VALUES ('Ice skating, average speed',413);
