
INSERT INTO foods(food,calories) VALUES ('Egg boiled','80');
INSERT INTO foods(food,calories) VALUES ('Egg Poached','80');
INSERT INTO foods(food,calories) VALUES ('Egg Fried','110');
INSERT INTO foods(food,calories) VALUES ('Egg Omelet','120');
INSERT INTO foods(food,calories) VALUES ('Bread slice','45');
INSERT INTO foods(food,calories) VALUES ('Bread slice with butter','90');
INSERT INTO foods(food,calories) VALUES ('Chapati','60');
INSERT INTO foods(food,calories) VALUES ('Puri','75');
INSERT INTO foods(food,calories) VALUES ('Paratha','150');
INSERT INTO foods(food,calories) VALUES ('Subji','150');
INSERT INTO foods(food,calories) VALUES ('Idli','100');
INSERT INTO foods(food,calories) VALUES ('Dosa Plain','120');
INSERT INTO foods(food,calories) VALUES ('Dosa Masala','250');
INSERT INTO foods(food,calories) VALUES ('Sambhar','150');
INSERT INTO foods(food,calories) VALUES ('Cooked Rice','120');
INSERT INTO foods(food,calories) VALUES ('Chapati','60');
INSERT INTO foods(food,calories) VALUES ('Puri','75');
INSERT INTO foods(food,calories) VALUES ('Paratha','150');
INSERT INTO foods(food,calories) VALUES ('Naan','150');
INSERT INTO foods(food,calories) VALUES ('Dal','150');
INSERT INTO foods(food,calories) VALUES ('Sambhar','150');
INSERT INTO foods(food,calories) VALUES ('Curd','100');
INSERT INTO foods(food,calories) VALUES ('Curry/Vegetable','150');
INSERT INTO foods(food,calories) VALUES ('Curry/Meat','175');
INSERT INTO foods(food,calories) VALUES ('Salad','100');
INSERT INTO foods(food,calories) VALUES ('Papad','45');
INSERT INTO foods(food,calories) VALUES ('Cutlet','75');
INSERT INTO foods(food,calories) VALUES ('Pickle','30');
INSERT INTO foods(food,calories) VALUES ('Soup/Clear','75');
INSERT INTO foods(food,calories) VALUES ('Soup/Heavy','75');
INSERT INTO foods(food,calories) VALUES ('Fruit (1 helping)','150');
INSERT INTO foods(food,calories) VALUES ('Tea/Black/without sugar','10');
INSERT INTO foods(food,calories) VALUES ('Coffee/Black/without sugar','10');
INSERT INTO foods(food,calories) VALUES ('Tea with milk & sugar','45');
INSERT INTO foods(food,calories) VALUES ('Coffee with milk & sugar','45');
INSERT INTO foods(food,calories) VALUES ('Milk without sugar','60');
INSERT INTO foods(food,calories) VALUES ('Milk with sugar','75');
INSERT INTO foods(food,calories) VALUES ('Soft Drinks','90');
INSERT INTO foods(food,calories) VALUES ('Beer(1 bottle)','200');
INSERT INTO foods(food,calories) VALUES ('Soda(1 bottle)','10');
INSERT INTO foods(food,calories) VALUES ('Alcohol neat','75');
INSERT INTO foods(food,calories) VALUES ('Porridge','150');
INSERT INTO foods(food,calories) VALUES ('Jam','30');
INSERT INTO foods(food,calories) VALUES ('Butter','50');
INSERT INTO foods(food,calories) VALUES ('Ghee(1 tsp)','50');
INSERT INTO foods(food,calories) VALUES ('Sugar(1 tsp)','30');
INSERT INTO foods(food,calories) VALUES ('Biscuit','30');
INSERT INTO foods(food,calories) VALUES ('Fried Nuts','300');
INSERT INTO foods(food,calories) VALUES ('Puddings','200');
INSERT INTO foods(food,calories) VALUES ('Ice-cream (1 cup)','200');
INSERT INTO foods(food,calories) VALUES ('Milk-Shake(1 glass)','200');
INSERT INTO foods(food,calories) VALUES ('Wafers(1 pkt)','120');
INSERT INTO foods(food,calories) VALUES ('Samosa','100');
INSERT INTO foods(food,calories) VALUES ('Bhel Puri/Pani Puri','150');
INSERT INTO foods(food,calories) VALUES ('Kebab(1 plate)','150');
INSERT INTO foods(food,calories) VALUES ('Indian sweets','150');
INSERT INTO foods(food,calories) VALUES ('Bread Slices with Butter & Jam/Cheese','120');
INSERT INTO foods(food,calories) VALUES ('Breakfast cereal with milk','130');
INSERT INTO foods(food,calories) VALUES ('Porridge & Milk','120');
INSERT INTO foods(food,calories) VALUES ('Sausage/bacon/ham','120');
INSERT INTO foods(food,calories) VALUES ('Potato mash','100');
INSERT INTO foods(food,calories) VALUES ('Potato fried','200');
INSERT INTO foods(food,calories) VALUES ('Sandwich large','250');
INSERT INTO foods(food,calories) VALUES ('Hamburger','250');
INSERT INTO foods(food,calories) VALUES ('Steak & Salad','300');
INSERT INTO foods(food,calories) VALUES ('Spaghetti & meat/sauce','450');
INSERT INTO foods(food,calories) VALUES ('Baked dish','400');
INSERT INTO foods(food,calories) VALUES ('Fried Chicken','200');
INSERT INTO foods(food,calories) VALUES ('Chinese noodles','450');
INSERT INTO foods(food,calories) VALUES ('Chinese Fried Rice','450');
INSERT INTO foods(food,calories) VALUES ('Pizza','400');
